name: push
on:
  push:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - ".github/images"
      - "README.md"
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: printenv
      - name: Run make push target
        run: make -C .github push

